namespace MekomonPublisher.Api.Models;

/// <summary>What the operator submits from the publish form.</summary>
public sealed class PublishRequest
{
    public required string RawText { get; init; }

    public required int CategoryId { get; init; }

    /// <summary>Either "publish" or "draft".</summary>
    public required string Status { get; init; }

    /// <summary>Index into <see cref="Images"/> of the one to use as the featured image.</summary>
    public required int FeaturedImageIndex { get; init; }

    public required IReadOnlyList<UploadedImage> Images { get; init; }
}

public sealed class UploadedImage
{
    public required string FileName { get; init; }

    public required byte[] Bytes { get; init; }

    /// <summary>
    /// Photo credit typed by the operator, e.g. "צילום: ישראל ישראלי". Never
    /// generated by Gemini: a credit is a factual claim about who took the
    /// photo, which the model has no way of actually knowing. Null or blank
    /// means no caption is added for this image at all, full stop.
    /// </summary>
    public string? Caption { get; init; }
}

/// <summary>What the API returns after a publish attempt.</summary>
public sealed class PublishResult
{
    public required bool Success { get; init; }

    public string? Title { get; init; }

    public string? Url { get; init; }

    public string? Status { get; init; }

    public required long ElapsedMs { get; init; }

    public string? Error { get; init; }
}
