namespace MekomonPublisher.Api.Models;

/// <summary>What the operator submits from the publish form.</summary>
public sealed class PublishRequest
{
    public required string RawText { get; init; }

    public required int CategoryId { get; init; }

    /// <summary>Either "publish" or "draft".</summary>
    public required string Status { get; init; }

    /// <summary>
    /// True (the default): Gemini rewrites <see cref="RawText"/> into the
    /// site's house style, picks the title/subtitle, and decides image
    /// placement. False: nothing is AI-generated - <see cref="Title"/> and
    /// <see cref="Subtitle"/> come from the operator and RawText is split
    /// into paragraphs mechanically. Either way the same
    /// <see cref="Models.GeneratedArticle"/> shape reaches
    /// <see cref="Services.GutenbergBuilder"/>, so publishing itself is
    /// identical downstream.
    /// </summary>
    public required bool UseAi { get; init; }

    /// <summary>Required, and used, only when <see cref="UseAi"/> is false.</summary>
    public string? Title { get; init; }

    /// <summary>Required, and used, only when <see cref="UseAi"/> is false.</summary>
    public string? Subtitle { get; init; }

    /// <summary>Index into <see cref="Images"/> of the one to use as the featured image.</summary>
    public required int FeaturedImageIndex { get; init; }

    public required IReadOnlyList<UploadedImage> Images { get; init; }
}

public sealed class UploadedImage
{
    public required string FileName { get; init; }

    public required byte[] Bytes { get; init; }

    /// <summary>
    /// Photo credit typed by the operator, e.g. "צילום: ישראל ישראלי". Never
    /// generated by Gemini: a credit is a factual claim about who took the
    /// photo, which the model has no way of actually knowing. Null or blank
    /// means no caption is added for this image at all, full stop.
    /// </summary>
    public string? Caption { get; init; }
}

/// <summary>What the API returns after a publish attempt.</summary>
public sealed class PublishResult
{
    public required bool Success { get; init; }

    public string? Title { get; init; }

    public string? Url { get; init; }

    public string? Status { get; init; }

    public required long ElapsedMs { get; init; }

    public string? Error { get; init; }
}
