using System.Xml.Linq;
using Microsoft.AspNetCore.DataProtection.Repositories;

namespace MekomonPublisher.Api.Services;

/// <summary>
/// Hands ASP.NET Core's Data Protection system exactly one pre-generated key,
/// forever, instead of a rotating ring backed by disk. Render's free tier has
/// no persistent disk: a redeploy, a health-check restart, or the instance
/// simply spinning down after idle and waking back up all recreate the
/// container's filesystem from scratch. A key ring persisted to that disk
/// (via PersistKeysToFileSystem) is gone the moment any of those happen,
/// which silently invalidates every logged-in operator's cookie - the 401s
/// this class exists to stop. An environment variable, unlike the disk,
/// survives all of those. Paired with DisableAutomaticKeyGeneration() so the
/// framework never tries to mint a second key it has nowhere durable to put.
/// </summary>
public sealed class FixedKeyXmlRepository(XElement key) : IXmlRepository
{
    public IReadOnlyCollection<XElement> GetAllElements() => [key];

    // Automatic key generation is disabled by the caller, so this should
    // never actually fire - but if it somehow did, there is nowhere durable
    // to write it on this host anyway, so a silent no-op is the honest
    // behavior rather than pretending to persist something that won't survive
    // the next restart.
    public void StoreElement(XElement element, string? friendlyName)
    {
    }
}

/// <summary>Captures the one key XML generated by <c>dotnet run -- generate-dp-key</c>, for printing to the console.</summary>
public sealed class CapturingXmlRepository : IXmlRepository
{
    public XElement? Captured { get; private set; }

    public IReadOnlyCollection<XElement> GetAllElements() => Captured is null ? [] : [Captured];

    public void StoreElement(XElement element, string? friendlyName) => Captured = element;
}
